services:
    db:
        image: mariadb:11.4-ubi9
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=password
            - MARIADB_DATABASE=db
            - MARIADBL_USER=user
            - MARIADB_PASSWORD=password
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:5.1
        restart: always
        ports:
        - 8090:80
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=password
        depends_on:
            - db

    php-base:
        build:
            context: .
            dockerfile: docker/Dockerfile
        image: php-base:latest
        environment:
            - PARALLEL_VERSION=1.2.5

    dev:
        build:
            context: .
            dockerfile: ./docker/dev/Dockerfile
        volumes:
            - ./src/:/app/src/
        ports:
            - 8010:8080
        environment:
            - WORKDIR=/app
        depends_on:
            - php-base
            - db

    apache:
        build: 
            context: .
            dockerfile: ./docker/apache/Dockerfile
        volumes:
            - ./src/:/app/src/
            - ./docker/apache/.htaccess:/app/src/public/.htaccess
        ports:
            - 8000:80
        depends_on:
            - php-base
            - db
