version: '3'
services:
    db:
        image: mysql:latest
        restart: unless-stopped
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - MYSQL_DATABASE=db
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
        ports:
            - 3306:3306

    phpmyadmin:
        image: phpmyadmin:latest
        ports:
            - 8090:80
        environment:
            - MYSQL_ROOT_PASSWORD=password
            - PMA_HOST=db
            - PMA_USER=root
            - PMA_PASSWORD=password
        depends_on:
            - db

    server:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
        volumes:
            - ./src/:/app/src/
        ports:
            - 8080:8080
        depends_on:
            - db
